spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # ??????
    url: jdbc:mysql://localhost:3306/sb?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root

  redis:
    client-name: 127.0.0.1
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml  # ???XML????
  type-aliases-package: com.opencode.demo.pojo  # ??????


